version: '3.7'

services:
  proxy:
    image: alebabai/ssh-proxy:latest
    build: .
    environment: 
      ADDRESSES: |-
        localhost:80
    volumes:
      - ./tmp:/tmp/ssh-proxy
    networks: 
      - internal

networks:
  internal:
    driver: bridge
