version: '3.7'

services:
  proxy:
    image: alebabai/ssh-proxy:latest
    build: .
    environment: 
      ADDRESSES: |-
        nginx:80
    volumes:
      - ./tmp:/tmp/ssh-proxy
    networks: 
      - internal

  nginx:
    image: nginx:latest
    networks: 
      - internal

networks:
  internal:
    driver: bridge

