#!/bin/bash

PREFIX="org.opencontainers.image"

docker build \
  --label $PREFIX.created=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
  --label $PREFIX.url=$SOURCE_REPOSITORY_URL \
  --label $PREFIX.source=$SOURCE_REPOSITORY_URL \
  --label $PREFIX.version=$DOCKER_TAG \
  --label $PREFIX.revision=$SOURCE_COMMIT \
  --label $PREFIX.vendor="alebabai" \
  --label $PREFIX.title="SSH-proxy" \
  --label $PREFIX.description="Dockerized SSH-proxy" \
  --label $PREFIX.authors="aliaksandr.babai@gmail.com" \
  --label $PREFIX.licenses=$(head -n 1 $PWD/LICENSE) \
  -t $IMAGE_NAME \
  .
