#!/bin/bash

PREFIX="org.opencontainers.image"

LABELS=(
$PREFIX.created=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
$PREFIX.url=$SOURCE_REPOSITORY_URL
$PREFIX.source=$SOURCE_REPOSITORY_URL
$PREFIX.version=$DOCKER_TAG
$PREFIX.revision=$SOURCE_COMMIT
$PREFIX.vendor="alebabai"
$PREFIX.title="SSH-proxy"
$PREFIX.description="Dockerized SSH-proxy"
$PREFIX.authors="aliaksandr.babai@gmail.com"
$PREFIX.licenses="$(head -n 1 $PWD/LICENSE)"
)

docker build --label "${LABELS[*]}" -t $IMAGE_NAME .
