#!/bin/bash

PREFIX="org.opencontainers.image"

docker build \
  --label $PREFIX.created=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
  --label $PREFIX.url=$(git remote get-url origin) \
  --label $PREFIX.source=$(git remote get-url origin) \
  --label $PREFIX.version=$DOCKER_TAG \
  --label $PREFIX.revision=$(git remote get-url origin) \
  --label $PREFIX.vendor="alebabai" \
  --label $PREFIX.title="SSH-proxy" \
  --label $PREFIX.description="Dockerized SSH-proxy" \
  --label $PREFIX.authors="aliaksandr.babai@gmail.com" \
  --label $PREFIX.licenses=$(head -n 1 $PWD/LICENSE) \
  -t $IMAGE_NAME \
  .
